# Generated by Django 6.0.2 on 2026-03-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysissession',
            options={'ordering': ['-analysis_date']},
        ),
        migrations.AddField(
            model_name='analysissession',
            name='ai_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='repo_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analyzer.repository'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='main_language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='FileMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('nloc', models.IntegerField(default=0)),
                ('ccn', models.FloatField(default=0.0)),
                ('commits', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_metrics', to='analyzer.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('nloc', models.IntegerField(default=0)),
                ('ccn', models.FloatField(default=0.0)),
                ('commits', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_metrics', to='analyzer.analysissession')),
            ],
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
