# Generated by Django 6.0.2 on 2026-04-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analysissession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='evolution_data',
            field=models.JSONField(default=list),
        ),
    ]
