# Generated by Django 6.0.2 on 2026-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysissession_evolution_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='author_activity',
            field=models.JSONField(default=list),
        ),
    ]
