# Generated by Django 6.0.2 on 2026-05-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analysissession_author_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
