# Generated by Django 6.0.2 on 2026-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_repository_is_private_repository_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='age_distribution',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='file_ownership',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='top_complex_files',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='filemetric',
            name='age_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filemetric',
            name='num_functions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filemetric',
            name='ownership',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filemetric',
            name='peak_ccn',
            field=models.FloatField(default=0.0),
        ),
    ]
