# Generated by Django 6.0.2 on 2026-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_analysissession_age_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetric',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
