# Generated by Django 6.0.2 on 2026-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_filemetric_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gitlab_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gitlab_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(default='github', max_length=50),
        ),
    ]
