# Generated by Django 6.0.2 on 2026-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_userprofile_gitlab_token_userprofile_gitlab_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='file_network',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
