# Generated by Django 6.0.2 on 2026-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_analysissession_file_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='analysis_mode',
            field=models.CharField(default='commits', max_length=20),
        ),
    ]
