# Generated by Django 6.0.2 on 2026-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_analysissession_analysis_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='pull_requests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
