# Generated by Django 6.0.2 on 2026-07-28 11:02

import analyzer.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_analysissession_issues_analysissession_pull_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_token',
            field=analyzer.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gitlab_token',
            field=analyzer.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
